services:
  - type: web
    name: trading-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    rootDir: backend
    envVars:
      - key: SECRET_KEY
        value: your-secret
      - key: TELEGRAM_TOKEN
        value: your-token
      - key: TELEGRAM_CHAT_ID
        value: your-chat-id
  - type: static
    name: trading-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    rootDir: frontend
