services:
  - type: web
    name: trading-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    rootDir: backend
    plan: starter
    envVars:
      - key: SECRET_KEY
        value: your-secret
      - key: TELEGRAM_TOKEN
        value: your-token
      - key: TELEGRAM_CHAT_ID
        value: your-chat-id

  - type: web
    name: trading-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist"
    rootDir: frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://trading-hsmu.onrender.com
